default: &default
  adapter: mysql2
  encoding: utf8
  charset: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: kaeshiuma
  password: kaeshiuma
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: kaeshiuma_development

test:
  <<: *default
  database: kaeshiuma_test

production:
  <<: *default
  database: heroku_9932072c7de3ab2
  username: bf7296609f3ff3
  password: <%= ENV['TESTAPP_DATABASE_PASSWORD'] %>
